### ISSUE TITLE
cloud-readiness ruleset lacks a 'name'

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/rulesets#36]
I don't see a 'name' here: https://github.com/konveyor/rulesets/blob/main/default/generated/cloud-readiness/ruleset.yaml

The impact this has when we run a report we get output like below, as I'm working through parsing multiple rulesets, I don't see a clear way to know the violations are from 'cloud-readiness'.

```
- description: This ruleset detects logging configurationsdetects logging configurations that may be problematic when migrating an application to a cloud environment.
  violations:
    session-00000:
      description: HTTP session replication (distributable web.xml)
      category: mandatory
      labels:
      - clustering
      - konveyor.io/source=java
      - konveyor.io/source=java-ee
      - konveyor.io/target=cloud-readiness
      incidents:
      - uri: file:///tmp/source-code/src/main/webapp/WEB-INF/web.xml
        message: "\n Session replication ensures that client sessions are not disrupted by node failure. Each node in the cluster shares information about ongoing sessions and can take over sessions if another node disappears. In a cloud environment, however, data in the memory of a running container can be wiped out by a restart.\n\n Recommendations\n\n * Review the session replication usage and ensure that it is configured properly.\n * Disable HTTP session clustering and accept its implications.\n * Re-architect the application so that sessions are stored in a cache backing service or a remote data grid.\n\n A remote data grid has the following benefits:\n\n * The application is more scaleable and elastic.\n * The application can survive EAP node failures because a JVM failure does not cause session data loss.\n * Session data can be shared by multiple applications.\n "
        variables:
          data: distributable
          innerText: ""
          matchingXML: ""
      links:
      - url: https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.3/html-single/getting_started_with_jboss_eap_for_openshift_container_platform/index#reference_clustering
        title: 'Getting Started with JBoss EAP for OpenShift Container Platform: Clustering'
      - url: https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.3/html-single/configuration_guide/index#jdg_externalize_http_sessions
        title: 'JBoss EAP:  Externalize HTTP Sessions to Red Hat Data Grid'
      - url: https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.3/html/development_guide/clustering_in_web_applications
        title: 'JBoss EAP: Clustering in Web Applications'
      - url: https://access.redhat.com/documentation/en-us/red_hat_data_grid/8.0/html-single/running_data_grid_on_openshift/index
        title: Running Data Grid on OpenShift
      - url: https://12factor.net/backing-services
        title: 'Twelve-Factor App: Backing services'
      - url: https://12factor.net/processes
        title: 'Twelve-Factor App: Processes'
      effort: 3
  unmatched:
  - embedded-cache-libraries-01000
  - embedded-cache-libraries-01000
  - embedded-cache-libraries-01000
  - embedded-cache-libraries-01000
  - embedded-cache-libraries-02000
  - embedded-cache-libraries-02000
  - embedded-cache-libraries-02000
  - embedded-cache-libraries-02000
  - embedded-cache-libraries-03000
  - embedded-cache-libraries-03000
  - embedded-cache-libraries-03000
  - embedded-cache-libraries-03000
  - embedded-cache-libraries-04000
  - embedded-cache-libraries-04000
  - embedded-cache-libraries-04000
  - embedded-cache-libraries-04000
  - embedded-cache-libraries-05000
  - embedded-cache-libraries-05000
  - embedded-cache-libraries-05000
  - embedded-cache-libraries-05000
  - embedded-cache-libraries-06000
  - embedded-cache-libraries-06000
  - embedded-cache-libraries-06000
  - embedded-cache-libraries-06000
  - embedded-cache-libraries-07000
  - embedded-cache-libraries-07000
  - embedded-cache-libraries-07000
  - embedded-cache-libraries-07000
  - embedded-cache-libraries-08000
  - embedded-cache-libraries-08000
  - embedded-cache-libraries-08000
  - embedded-cache-libraries-08000
  - embedded-cache-libraries-09000
  - embedded-cache-libraries-09000
  - embedded-cache-libraries-09000
  - embedded-cache-libraries-09000
  - embedded-cache-libraries-10000
  - embedded-cache-libraries-10000
  - embedded-cache-libraries-10000
  - embedded-cache-libraries-10000
  - embedded-cache-libraries-11000
  - embedded-cache-libraries-11000
  - embedded-cache-libraries-11000
  - embedded-cache-libraries-11000
  - embedded-cache-libraries-12000
  - embedded-cache-libraries-12000
  - embedded-cache-libraries-12000
  - embedded-cache-libraries-12000
  - embedded-cache-libraries-13000
  - embedded-cache-libraries-13000
  - embedded-cache-libraries-13000
  - embedded-cache-libraries-13000
  - embedded-cache-libraries-14000
  - embedded-cache-libraries-14000
  - embedded-cache-libraries-14000
  - embedded-cache-libraries-14000
  - embedded-cache-libraries-15000
  - embedded-cache-libraries-15000
  - embedded-cache-libraries-15000
  - embedded-cache-libraries-15000
  - embedded-cache-libraries-16000
  - embedded-cache-libraries-16000
  - java-corba-00000
  - java-rmi-00000
  - java-rmi-00000
  - java-rmi-00000
  - java-rmi-00000
  - java-rmi-00001
  - java-rmi-00001
  - java-rmi-00001
  - java-rmi-00001
  - java-rpc-00000
  - java-rpc-00000
  - jca-00000
  - jca-00000
  - jni-native-code-00000
  - jni-native-code-00000
  - jni-native-code-00001
  - local-storage-00001
  - local-storage-00001
  - local-storage-00002
  - local-storage-00002
  - local-storage-00003
  - local-storage-00003
  - local-storage-00004
  - local-storage-00004
  - local-storage-00005
  - local-storage-00005
  - local-storage-00006
  - localhost-http-00001
  - localhost-jdbc-00002
  - localhost-ws-00003
  - logging-0000
  - logging-0000
  - logging-0000
  - logging-0000
  - logging-0001
  - logging-0001
  - logging-0001
  - logging-0001
  - mail-00000
  - mail-00000
  - session-00001
  - session-00001
  - socket-communication-00000
  - socket-communication-00000
  - socket-communication-00001
  - socket-communication-00001
```
