### ISSUE TITLE
Seeing svg files as being matched for "Replace the Java EE version with the Jakarta equivalent", ruleid: javaee-to-jakarta-namespaces-00035

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/rulesets#41]
I'm seeing a number of .svg files being flagged in the report as incidents of "javaee-to-jakarta-namespaces-00035".

Rule is from:
https://github.com/konveyor/rulesets/blob/main/default/generated/eap8/120-javaee-to-jakarta-namespaces.windup.yaml#L704C19-L704C19

Example:
```
javaee-to-jakarta-namespaces-00035:
      description: Replace the Java EE version with the Jakarta equivalent
      category: mandatory
      labels:
      - konveyor.io/source
      - konveyor.io/target=eap
      - konveyor.io/target=eap8
      - konveyor.io/target=jakarta-ee
      - konveyor.io/target=jakarta-ee9+
      incidents:
      - uri: file:///tmp/source-code/src/main/webapp/bower_components/angular-patternfly/dist/docs/img/OpenShift-Logo-NoText.svg
        message: '`beans_1_1.xsd`: In the root tag, replace the `version` attribute value with `3.0`'
        codeSnip: "  1  <?xml version=\"1.0\" encoding=\"utf-8\"?>\n  2  <!-- Generator: Adobe Illustrator 19.2.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->\n  3  <svg version=\"1.1\"\n  4  \t id=\"svg4242\" xmlns:cc=\"http://creativecommons.org/ns#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n  5  \t xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" x=\"0px\" y=\"0px\" viewBox=\"0 0 200 199.7\"\n  6  \t style=\"enable-background:new 0 0 200 199.7;\" xml:space=\"preserve\">\n  7  <style type=\"text/css\">\n  8  \t.st0{fill:#C32034;}\n  9  \t.st1{fill:#DB212F;}\n 10  \t.st2{fill:#EA2227;}\n 11  \t.st3{fill:#AD213A;}\n 12  \t.st4{fill:#BA2034;}\n 13  </style>\n 14  <g id=\"g3921\">\n 15  \t<g id=\"g3927\" transform=\"translate(304.96 416.03)\">\n 16  \t\t<path id=\"path3929\" class=\"st0\" d=\"M-235.4-323l-23.3,8.5c0.3,3.8,0.9,7.5,1.9,11.1l22.1-8C-235.4-315.4-235.7-319.2-235.4-323\"/>\n 17  \t</g>\n 18  \t<g id=\"g3931\" transform=\"translate(418.75 444.5)\">\n 19  \t\t<path id=\"path3933\" class=\"st0\" d=\"M-246.2-377.3c-1.6-3.3-3.5-6.6-5.6-9.6l-23.3,8.5c2.7,2.8,5,5.9,6.9,9.2\n 20  \t\t\tC-268.3-369.3-246.2-377.3-246.2-377.3z\"/>\n 21  \t</g>\n 22  \t<g id=\"g3935\" transform=\"translate(362.11 451.79)\">\n 23  \t\t<path id=\"path3937\" class=\"st1\" d=\"M-240.8-391.2c4.8,2.2,9,5.4,12.6,9l23.3-8.5c-6.4-9-15.3-16.6-26-21.6\n 24  \t\t\tc-33.3-15.5-73-1.1-88.5,32.2c-5,10.8-6.9,22.2-6,33.3l23.3-8.5c0.4-5.1,1.6-10.1,3.9-15C-288.2-391.9-262.5-401.2-240.8-391.2\"/>\n 25  \t</g>\n 26  \t<g id=\"g3939\" transform=\"translate(282.86 395.05)\">\n 27  \t\t<path id=\"path3941\" class=\"st2\" d=\"M-233.3-283.1l-22.1,8c2,8,5.6,15.7,10.4,22.6l23.2-8.5C-227.7-267.1-231.7-274.8-233.3-283.1\"\n 28  \t\t\t/>\n 29  \t</g>\n 30  \t<g id=\"g3943\" transform=\"translate(389.56 404.75)\">\n 31  \t\t<path id=\"path3945\" class=\"st1\" d=\"M-243.4-301.6c-0.4,5.1-1.7,10.1-3.9,15c-10.1,21.6-35.9,31.1-57.5,20.9c-4.8-2.2-9-5.4-12.6-9\n 32  \t\t\tl-23.2,8.5c6.4,9,15.2,16.6,26,21.6c33.3,15.5,73,1.1,88.5-32.2c5-10.8,6.9-22.2,6-33.3L-243.4-301.6L-243.4-301.6z\"/>\n 33  \t</g>\n 34  \t<g id=\"g3947\" transform=\"translate(395.89 436.18)\">\n 35  \t\t<path id=\"path3949\" class=\"st2\" d=\"M-244-361.5l-22.1,8c4.1,7.4,6.1,15.9,5.4,24.4l23.2-8.5C-238.1-345.8-240.4-353.9-244-361.5\"\n 36  \t\t\t/>\n 37  \t</g>\n 38  \t<g id=\"g3951\" transform=\"translate(279.22 406.66)\">\n 39  \t\t<path id=\"path3953\" class=\"st3\" d=\"M-232.9-305.2l23.2-8.4l-0.1,4.6l-22.4,8.3C-232.2-300.7-232.9-305.2-232.9-305.2z\"/>\n 40  \t</g>\n 41  \t<g id=\"g3955\" transform=\"translate(386.73 445.86)\">\n 42  \t\t<path id=\"path3957\" class=\"st3\" d=\"M-243.1-379.9l23.6-8l2.5,3.6l-22.9,8C-240-376.2-243.1-379.9-243.1-379.9z\"/>\n 43  \t</g>\n 44  \t<g id=\"g3959\" transform=\"translate(282.04 365.71)\">\n 45  \t\t<path id=\"path3961\" class=\"st4\" d=\"M-233.2-227.2l23.2-8.3l7,6.5l-24.4,9C-227.3-220-233.2-227.2-233.2-227.2z\"/>\n 46  \t</g>\n 47  \t<g id=\"g3963\" transform=\"translate(415.68 414.03)\">\n 48  \t\t<path id=\"path3965\" class=\"st4\" d=\"M-245.9-319.2l-23.6,8.4l-1.7,9.3l25.2-8.8C-246.1-310.4-245.9-319.2-245.9-319.2z\"/>\n 49  \t</g>\n 50  </g>\n 51  </svg>\n"
        lineNumber: 3
        variables:
          matchingText: version="1.1"


```

Reproducer:
1. `git clone https://github.com/deewhyweb/eap-coolstore-monolith.git coolstuff-javaee`
2. `./kantra analyze -i ./coolstuff-javaee -t "quarkus" -t "jakarta-ee" -t "jakarta-ee8+" -t "jakarta-ee9+" -t "cloud-readiness" -o ./out --overwrite`
